navikt/arbeidssokerregistrering

- src/frontend/src/ducks/api.ts
> FO-230 Fiks mangler NAV_CSRF_PROTECTION header cookie ved post

- src/frontend/src/ducks/api.ts
Fiks set header NAV_CSRF_PROTECTION
getCookie funksjon ble ikke kalt
> FO-230 FIKS, getCookie funksjon ble ikke kalt

- src/middleware/metrics-middleware.ts
> [KAIZEN-0] Metrikk på antall som starter på registrering

- src/sider/registrert/registrert.tsx
> [KAIZEN-0] Metrikk på antall som klikker på visdagpenger etter

- src/routes.test.tsx
Enhetstester for å verifisere at man blir redirectet til rett sted
> FO-1698: Legge til flere enhetstester på routes

- integration/browserstack-runner.js
Legge til litt logging for feilsøking og returnere feilkode når tester feiler så travis bygget skal feile
> KAIZEN-0: For at travis bygg skal feile nar tester feiler

- integration/browserstack-runner.js
- package-lock.json
- package.json
Printer ut feilmelding og avslutter kjøring hvis det ikke er nok ledige browserstacksesjoner ledige
> FO-1826: Legge inn sjekk på kjørende browserstacksesjoner

- package-lock.json
- package.json
Oppdatere testcafe for å få med feilretting
> FO-1826: Oppdatere testcafe

- integration/browserstack-runner.js
- integration/registrering.test.ts
- integration/runner.js
- integration/uu.test.ts
Endret port, ref:
https://www.browserstack.com/question/664
Endret fra samsung galaxy til google nexus, work around for:
https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/25
https://github.com/DevExpress/testcafe/issues/2318
> FO-1826: Endre til port som er støttet av browserstack

- src/sider/registrert/aksjonspanel/registrert-aksjonspanel.tsx
- src/tekster/hjelpetekster/duernaregistrert/duernaregistrert-knapp-ikke-na_nb.txt
- src/tekster/hjelpetekster/duernaregistrert/duernaregistrert-ordinaer-element_nb.txt
- src/utils/konstanter.ts
Legger inn lenke direkte til DP søknad for ordinære registreringer
> [FO-2216] - Lenke til DP søknad

- src/mocks/HerokuappEndreMockRegistreringLoep/herokuapp-endre-mock-registrering-loep.tsx
- src/mocks/registreringstatus-mock.ts
Legger inn velger for servicegrupper og formidlingsgrupper i demoen
> [KAIZEN-0] - Mockoppdatering

- package.json
- src/mocks/HerokuappEndreMockRegistreringLoep/herokuapp-endre-mock-registrering-loep.tsx
- src/sider/allerede-registrert/allerede-registrert.less
- src/sider/allerede-registrert/allerede-registrert.tsx
Sender med state så budskapet kan tilpasses de ulike gruppene på allerede registrert.
Oppdaterer demo-settings så man kan bytte service- og forbidlingsgrupper
> [KAIZEN-0] - formidlingsgrupper og servicegrupper til allerederegistrert

- src/komponenter/alertstripe.less
- src/sider/allerede-registrert/allerede-registrert.tsx
- src/tekster/hjelpetekster/allerede-registrert/allerede-registrert-iarbsmelding_nb.html
Legger samme melding som på ditt NAV for arbeidssøkere dersom noen med IARBS kommer til "allerede registrert" siden.
> [KAIZEN-0] - ny melding til iarbs på allerede registrert

- src/komponenter/info-kort/info-kort.tsx
- src/komponenter/initialdata/stepup.tsx
- src/komponenter/lenke-med-chevron/lenke-med-chevron.tsx
- src/metrikker/amplitude-utils.ts
- src/mocks/autentiseringsinfo-mock.ts
- src/tekster/hjelpetekster/stepup/beskrivelse-manuell-hjelp-stepup_nb.html
- src/tekster/hjelpetekster/stepup/beskrivelse-manuell-hjelp-stepup_nb.txt
- src/tekster/hjelpetekster/stepup/manuell-hjelp-lenketekst_nb.txt
Forbedret teksten for fonn mitt NAV-kontor.
La inn støtte for html på infokort beskrivelsen
> [KAIZEN-0] - FAGSYSTEM-80549 ny tekst og støtte for html på infokort 

- package-lock.json
- package.json
- src/metrikker/amplitude-utils.ts
- src/metrikker/uni-logger.ts
Legger inn deviceId, appname og appversion på all logging via uniLogger
> [KAIZEN-0] - Logger deviceId

- src/middleware/metrics-middleware.ts
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/info-for-ikke-arbeidssoker-uten-oppfolging.tsx
Legger den til i tags på inngang.type.
Pynter litt på koden andre steder
> [KAIZEN-0] - mer underOppfolging metrikk

- src/ducks/registreringstatus.ts
- src/mocks/HerokuappEndreMockRegistreringLoep/herokuapp-endre-mock-registrering-loep.tsx
- src/mocks/registreringstatus-mock.ts
- src/sider/allerede-registrert/allerede-registrert.tsx
- src/sider/allerede-registrert/iarbs-plaster.tsx
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/info-for-ikke-arbeidssoker-uten-oppfolging.tsx
Legger til rettighetsgruppe på registreringsstatus og metrikker
> [KAIZEN-0] - rettighetsgruppe

- src/ducks/feature-toggles.ts
- src/mocks/feature-toggles-mock.ts
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/info-for-ikke-arbeidssoker-uten-oppfolging.less
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/info-for-ikke-arbeidssoker-uten-oppfolging.tsx
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/ny-melding.tsx
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/original-melding.tsx
- src/utils/konstanter.ts
Gi bedre svar for de som er inne med registreringType SPERRET
Styres fra unleash vha toggle `arbeidssokerregistrering.sperret.ny-versjon`
> [KAIZEN-0] - ny side for brukere som har SPERRET

- src/ducks/feature-toggles.ts
- src/mocks/HerokuappEndreMockRegistreringLoep/herokuapp-endre-mock-registrering-loep.tsx
- src/mocks/feature-toggles-mock.ts
Slås på via unleash og `arbeidssokerregistrering.kontaktmeg.kontor-5701`
> [KAIZEN-0] - legger inn NAV Falkenborg på kontakt-meg bruker

- src/ducks/feature-toggles.ts
- src/komponenter/initialdata/hent-initial-data.tsx
- src/sider/tjeneste-oppdateres.less
Når featuretoggle om nedetid er slått på vil brukeren nå få beskjed om dette før innloggingen.
> Flytter varsel om nedetid _foran_ innlogging (patch)

- .travis.yml
Jeg har i tillegg slettet webhooken på GitHub som sendte events til Travis.
> Fjerner config for travis fordi Travis ikke er i bruk

- src/komponenter/innholdslaster/innholdslaster.tsx
- src/sider/fullfor/feilhandtering/feilmelding-brukers-status-ugyldig.tsx
- src/sider/registrert/registrert.tsx
- logger feil i innholdslaster
- logger success fordelt på registreringType
> Legger logg på start og slutt (patch)

- src/sider/allerede-registrert/allerede-registrert.tsx
- src/sider/allerede-registrert/iarbs-plaster.tsx
- src/sider/allerede-registrert/melding.tsx
- oppdaterer melding med alternativer for hensikt
- legger amplitude på svarene
> Oppdaterer melding på det originale plasteret (patch)

- src/mocks/feature-toggles-mock.ts
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/original-melding.tsx
Nå er både ny og original melding samme versjon så vi kan jobbe videre med ny bak samme flagg.
> Legger inn tidligere featuretogglet sperret side som original (patch)

- src/sider/allerede-registrert/melding.tsx
- Legger inn link til arbeidsplassen for de som har til hensikt å opprette CV
> Arbeidsplassen visning

- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/ny-melding.tsx
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/original-melding.tsx
- legger inn id på arbeidsplassen lenke slik at klikk logges
> Fix arbeidsplassen

- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/ny-melding.tsx
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/original-melding.tsx
- legger til finner ikke det jeg leter etter
- endrer tekst på lenken til arbeidsplassen.no
> Oppdaterer alternativer og tekst

- src/sider/allerede-registrert/iarbs-plaster.tsx
- legger inn valg for cv
- legger inn valg for finner ikke det jeg leter etter
- fronter dialog foran telefon
> Får pilot i sync med vanlig allerede registrert side

- src/middleware/metrics-middleware.ts
- src/sider/info-for-ikke-arbeidssoker-uten-oppfolging/melding.tsx
- src/utils/antall-uker-sykmeldt.ts
- Legger inn spm på "sperret" om ikk krav på sykepenger
- Endrer logging av kun førstevalg til telling av antall valg som er gjort
- Lint fikser
> Andre ytelser

- src/metrikker/uni-logger.ts
- src/sider/registrert/aksjonspanel/registrert-aksjonspanel.tsx
- src/sider/tjeneste-oppdateres.tsx
- src/tekster/hjelpetekster/duernaregistrert/duernaregistrert-ordinaer-normaltekst_nb.html
- src/tekster/hjelpetekster/duernaregistrert/duernaregistrert-ordinaer-systemtittel_nb.txt
- legger inn lenke til engelsk søknadsskjema for dagpenger
- legger inn uniLogger på knappevalg
> Ny kvitteringsside

- src/ducks/api.ts
- src/ducks/feature-toggles.ts
- src/komponenter/oppholdstillatelse/kontakt-meg-melding.less
- src/komponenter/oppholdstillatelse/kontakt-meg-melding.tsx
- src/mocks/feature-toggles-mock.ts
- src/mocks/mocks.ts
- src/sider/fullfor/feilhandtering/feilmelding-brukers-status-ugyldig.tsx
- Legger inn featuretoggle arbeidssokerregistrering.oppholdstillatelse.kontakt-bruker
- Lager ny kontakt bruker oppgave på de som mangler oppholdstillatelse
- Poster med OppgaveType til opprett oppgave api
> Kontakt bruker oppholdstillatelse

- src/komponenter/oppholdstillatelse/kontakt-meg-melding.tsx
- Forbedret tekster på norsk
- La inn engelsk på suksess og feilsider
> Oppholdstillatelse kontakt nye tekster

- package-lock.json
- package.json
- src/komponenter/oppholdstillatelse/kontakt-meg-melding.tsx
- src/mocks/feature-toggles-mock.ts
- src/utils/pretty-print-dato.ts
- Regner ut dato i istedet for å skrive 2 virkedager
> Endrer 2 virkedager til utregning av dato (patch)

- .github/workflows/deploy.yml
- src/mocks/mocks.ts
Synkron kjøring av tester og ordinær respons på startregistrering i demo
> Satt på ordinær respons på startregistrering

- package-lock.json
- package.json
- src/mocks/mocks.ts
- Oppdateringer etter råd fra Snyk
- Pynting for lint
> Snyk 20200622

- package-lock.json
- package.json
samleoppdatering etter snyks innspill
> Snyk 20200701

- package-lock.json
- package.json
> Snyk 20200703

- package-lock.json
- package.json
Dagens anbefalinger fra Snyk, samlet i en haug.
> Snyk 20200810

- package-lock.json
- package.json
Dagens oppdateringer anbefalt av Snyk
> Snyk 20200811

- package-lock.json
- package.json
> Oppdatere avhengigheter 20200812

- package-lock.json
- package.json
> Snyk 20200812

- package-lock.json
- package.json
Dagens fra Snyk pluss noen til
> Snyk 20200817

- package-lock.json
- package.json
Oppdatering fra snyk, pluss et par andre som var klare
> Snyk 20200825

- .github/workflows/deploy.yml
- cypress.json
Skrur av venting på animasjoner under testing,
> Cypress fix

- package-lock.json
- package.json
Oppdateringer fra Snyk og en del andre avhengigheter som var modne for oppdatering.
> Snyk 20201012

- package-lock.json
- src/metrikker/amplitude-utils.ts
- src/sider/registrert/aksjonspanel/reaktivert-aksjonspanel.tsx
- src/sider/registrert/registrert.tsx
- tsconfig.json
- Lager ny kvittering for de som reaktiveres så vi kan spisse informasjonen
> Ny kvittering for reaktiverte

- package-lock.json
- src/middleware/metrics-middleware.ts
- logger til Amplitude hvilken situasjon bruker kommer fra
> Amplitude kommer fra

- src/tekster/hjelpetekster/fullfor/fullfor-les-mer-CV_nb.txt
På fullfør siden endres teksten under punktet CV fra
- Når du fullfører registreringen, vil du få en oppgave i aktivitetsplanen om at du må fylle ut CV-en din. Det er viktig at du holder CV-en din oppdatert slik at du er synlig for arbeidsgivere.
til
- Det er viktig at du holder CV-en din oppdatert.
> Endrer teksten til - det er viktig at du holder CVen din oppdatert

- package-lock.json
- src/komponenter/kommer-fra/kommerfra.tsx
- src/sider/registrert/aksjonspanel/dpsoknad-aksjonspanel.tsx
- src/sider/registrert/registrert.tsx
- src/sider/startside/registrering-arbeidssoker.tsx
Det kan se ut til at en del av de som ikke har registrert seg som arbeidssøker når de skal søke dagpenger ikke vender tilbake til dagpengesøknaden etter fullført registrering.
Vi ønsker å se på muligheten for å automatisk sende disse brukere tilbake til dagpengesøknaden etter registrering.
Dette er en første proof of concept i så måte. Den tar vare på et parameter `kommerFra` og dersom dette finnes vises en annen kvittering som presiserer at man må fortsette søknad om dagpenger.
> Poc return to sender

- package-lock.json
- package.json
Oppdaterer avhengigheter forslått av Snyk
> Snyk 2021 11 29
